speisekarte = [
    {"Kategorie": "Getränk", "Speise": "Pappiger Milkshake", "Preis (€)": 3.5},
    {"Kategorie": "Getränk", "Speise": "Müffelnde Cola", "Preis (€)": 2.0},
    {"Kategorie": "Getränk", "Speise": "Sabberiger Softdrink", "Preis (€)": 2.2},
    {"Kategorie": "Getränk", "Speise": "Käselüftender Soda", "Preis (€)": 2.5},
    {"Kategorie": "Vorspeise", "Speise": "Gammelige Onion Rings", "Preis (€)": 4.0},
    {"Kategorie": "Vorspeise", "Speise": "Bröselige Nachos", "Preis (€)": 4.5},
    {"Kategorie": "Vorspeise", "Speise": "Matschepampige Mozzarella Sticks", "Preis (€)": 3.8},
    {"Kategorie": "Vorspeise", "Speise": "Quatschiger Salat", "Preis (€)": 3.2},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Ranziger Burger", "Preis (€)": 6.5},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Knusprig-Matschige Pommes", "Preis (€)": 2.8},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Schmierlappiger Cheeseburger", "Preis (€)": 5.9},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Wabberiger Hotdog", "Preis (€)": 4.2},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Zotteliger Wrap", "Preis (€)": 5.3},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Schmaddeliger Chickenburger", "Preis (€)": 5.8},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Brotzeliger Fishburger", "Preis (€)": 6.0},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Quakige Quesadilla", "Preis (€)": 4.7},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Zähschleimiger Burrito", "Preis (€)": 6.4},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Matschfrische Pizza", "Preis (€)": 7.5},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Käsefußige Tenders", "Preis (€)": 4.6},
    {"Kategorie": "Hauptmahlzeit", "Speise": "Käsig-Schleimige Wings", "Preis (€)": 5.0},
    {"Kategorie": "Nachspeise", "Speise": "Matschpampeartiger Donut", "Preis (€)": 2.5},
    {"Kategorie": "Nachspeise", "Speise": "Schmodderiger Muffin", "Preis (€)": 2.8},
    {"Kategorie": "Nachspeise", "Speise": "Wurstiger Brownie", "Preis (€)": 3.0},
    {"Kategorie": "Nachspeise", "Speise": "Sabberleckerer Pancake", "Preis (€)": 3.2},
    {"Kategorie": "Nachspeise", "Speise": "Klätschige Waffle", "Preis (€)": 3.5},
    {"Kategorie": "Nachspeise", "Speise": "Verschimmeltes Garlic Bread", "Preis (€)": 2.9},
    {"Kategorie": "Nachspeise", "Speise": "Käseschimmeliger Croissant", "Preis (€)": 2.6},
    {"Kategorie": "Nachspeise", "Speise": "Muffeliges Ice Cream", "Preis (€)": 2.7}
]
