import random

class Mahlzeit:

    adjektive = [
        "Matschepampig",
        "Schlabberig",
        "Gammelig",
        "Ranzig",
        "Müffelnd",
        "Pampig",
        "Matschig",
        "Quatschig",
        "Glibberig",
        "Schleimig",
        "Wabberig",
        "Furztriefend",
        "Modrig",
        "Käsig",
        "Muffelig",
        "Bröselig",
        "Schlabbrig",
        "Rotzig",
        "Schlotzig",
        "Klumpig",
        "Ranzelbummelig",
        "Batzig",
        "Miefend",
        "Gatschig",
        "Schmierig",
        "Zerlumpt",
        "Schmodderig",
        "Versifft",
        "Brabbelig",
        "Knorzig",
        "Quakig",
        "Schmaddelig",
        "Brotzelig",
        "Krümelig",
        "Matschknusprig",
        "Verdorben",
        "Klebberig",
        "Schmierlappig",
        "Zottelig",
        "Schlunzig",
        "Muffig",
        "Rotzig",
        "Zähschleimig",
        "Schubbelig",
        "Käsefußig",
        "Matschbrotig",
        "Verwabbert",
        "Labberig",
        "Quatschbrotig",
        "Rotzfrech",
        "Matscheklumpig",
        "Schleimig",
        "Stinkstiefelig",
        "Brotzelig",
        "Pupsig",
        "Schmotzig",
        "Matschfrisch",
        "Sabberig",
        "Klätschnass",
        "Ranzkäseartig",
        "Zwiebelig",
        "Brotig",
        "Fetttriefend",
        "Knüppelig",
        "Klumpig",
        "Glitschig",
        "Schrottig",
        "Pappig",
        "Stinkig",
        "Furzig",
        "Feuchtbröselig",
        "Schleimhautig",
        "Knorpsig",
        "Bratzig",
        "Verschimmelt",
        "Muffelkäseartig",
        "Schwabbelig",
        "Wurstig",
        "Krümelig",
        "Klatschnass",
        "Sabberlappig",
        "Quaddelig",
        "Rotzbrotig",
        "Labbrig",
        "Schlabbrig",
        "Quatschig",
        "Schmandig",
        "Matschpampeartig",
        "Quiekig",
        "Ranzverziert",
        "Schmutzig",
        "Zerlumpft",
        "Käselüftend",
        "Sabberlecker",
        "Schmodderkäseartig",
        "Verschmutzt",
        "Schleimkäse",
        "Gatschbrotig",
        "Käseschimmelig",
        "Klätschig",
        "Bröselmatschig",
        "Schleimtropfend",
        "Pampig-müffelig",
        "Stinkesauer"
    ]


    mahlzeiten = [
        "Burger",
        "Pommes",
        "Nuggets",
        "Hotdog",
        "Wrap",
        "Pizza",
        "Salat",
        "Taco",
        "Burrito",
        "Schnitzel",
        "Fries",
        "Sandwich",
        "Chicken",
        "Cheeseburger",
        "Milkshake",
        "Soda",
        "Cola",
        "Nachos",
        "Donut",
        "Onion-Rings",
        "Muffin",
        "Brownie",
        "Wings",
        "Chickenburger",
        "Fishburger",
        "Bagel",
        "Croissant",
        "Pita",
        "Falafel",
        "Pancakes",
        "Waffel",
        "Salami-Pizza",
        "Cheeseballs",
        "Curly-Fries",
        "Mozzarella-Sticks",
        "Softdrink",
        "Ice-Cream"
    ]

    @classmethod
    def generiere(cls, anzahl: int=3):

        if anzahl < 2:
            raise ValueError(
                "Parameter 'anzahl' sollte 2 oder groesser sein!"
            )
        
        adjektive_list = list(cls.adjektive)
        adjektive = []
        for k in range(anzahl - 1):
            n = random.randint(0, len(adjektive_list) - 1)
            adjektive.append(adjektive_list.pop(n))

        return " ".join(
            [
                "-".join(adjektive),
                random.choice(cls.mahlzeiten)
            ]
        )
